# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X9M1gh53Yq5ZnuSb9QW364EA8pIs-0K
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import numpy as np
# 
# # โหลดโมเดลที่บันทึกไว้
# with open('model.pkl', 'rb','joblib') as file:
#     model = pickle.load(file)
# 
# # ส่วนติดต่อผู้ใช้ของ Streamlit
# st.title("Prediction Web App")
# st.write("ป้อนข้อมูลเพื่อทำนายผลลัพธ์ด้วยโมเดลที่โหลด")
# 
# # สร้างอินพุตสำหรับผู้ใช้ป้อนข้อมูล
# feature_1 = st.number_input("Feature 1", min_value=0.0, max_value=100.0, value=50.0)
# feature_2 = st.number_input("Feature 2", min_value=0.0, max_value=100.0, value=50.0)
# 
# # เมื่อผู้ใช้กดปุ่ม "Predict"
# if st.button("Predict"):
#     # จัดรูปแบบข้อมูลอินพุตเป็น array
#     input_data = np.array([[feature_1, feature_2]])
# 
#     # ทำการพยากรณ์
#     prediction = model.predict(input_data)
# 
#     # แสดงผลลัพธ์
#     st.write("ผลลัพธ์ที่พยากรณ์ได้คือ:", prediction[0])
#